"""added cascade deletion

Revision ID: 0be791d3687e
Revises: e997461bc791
Create Date: 2023-07-27 00:37:15.488174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0be791d3687e'
down_revision = 'e997461bc791'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
