"""Added Files table2

Revision ID: 1b46111e8e5b
Revises: d80a0a18dfaf
Create Date: 2023-07-25 00:09:16.260009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b46111e8e5b'
down_revision = 'd80a0a18dfaf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
