"""Added postLikes table

Revision ID: 216bc9d094ca
Revises: d03989b82820
Create Date: 2023-07-18 22:29:30.955832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '216bc9d094ca'
down_revision = 'd03989b82820'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('postLikes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_postLikes_id'), 'postLikes', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_postLikes_id'), table_name='postLikes')
    op.drop_table('postLikes')
    # ### end Alembic commands ###
