"""added cascade deletion3

Revision ID: 46051a315cb3
Revises: 5be5fce4524f
Create Date: 2023-07-27 00:51:32.469035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46051a315cb3'
down_revision = '5be5fce4524f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
