"""added cascade deletion2

Revision ID: 5be5fce4524f
Revises: 0be791d3687e
Create Date: 2023-07-27 00:45:19.704201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5be5fce4524f'
down_revision = '0be791d3687e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
