"""added cascade deletion4.0

Revision ID: 9d31a9b60611
Revises: 46051a315cb3
Create Date: 2023-07-27 01:04:46.152480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d31a9b60611'
down_revision = '46051a315cb3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('post_creator_id_fkey', 'post', type_='foreignkey')
    op.create_foreign_key(None, 'post', 'user', ['creator_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('postLikes_user_id_fkey', 'postLikes', type_='foreignkey')
    op.drop_constraint('postLikes_post_id_fkey', 'postLikes', type_='foreignkey')
    op.create_foreign_key(None, 'postLikes', 'post', ['post_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'postLikes', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('user_post_creator_id_fkey', 'user_post', type_='foreignkey')
    op.drop_constraint('user_post_post_id_fkey', 'user_post', type_='foreignkey')
    op.create_foreign_key(None, 'user_post', 'post', ['post_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_post', 'user', ['creator_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_post', type_='foreignkey')
    op.drop_constraint(None, 'user_post', type_='foreignkey')
    op.create_foreign_key('user_post_post_id_fkey', 'user_post', 'post', ['post_id'], ['id'])
    op.create_foreign_key('user_post_creator_id_fkey', 'user_post', 'user', ['creator_id'], ['id'])
    op.drop_constraint(None, 'postLikes', type_='foreignkey')
    op.drop_constraint(None, 'postLikes', type_='foreignkey')
    op.create_foreign_key('postLikes_post_id_fkey', 'postLikes', 'post', ['post_id'], ['id'])
    op.create_foreign_key('postLikes_user_id_fkey', 'postLikes', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.create_foreign_key('post_creator_id_fkey', 'post', 'user', ['creator_id'], ['id'])
    # ### end Alembic commands ###
