"""Added Files table

Revision ID: d80a0a18dfaf
Revises: 7d5a5cea00cb
Create Date: 2023-07-25 00:07:24.907812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd80a0a18dfaf'
down_revision = '7d5a5cea00cb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
